# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='user_groups.UserDetail'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_groups.UserDetail'),
        ),
    ]
